version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    user: root
    ports:
      - "8080:8080"       # Jenkins UI
      - "50000:50000"     # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:ro # Mount local SSH configuration into Jenkins container
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Disable Jenkins setup wizard (Optional)
    restart: always

volumes:
  mongo-data:
  jenkins_home:
